/**
 * OrderRepository — port for persisting and querying Order entities.
 *
 * Implementation: src/infra/repositories/PrismaOrderRepository.ts
 * Tests:          src/infra/payment/InMemoryOrderRepository.ts
 */

import type { Result } from "@/domain/shared/Result";
import type { Order } from "@/domain/entities/Order";
import type { PaymentStatus } from "@/domain/values/PaymentStatus";

export type OrderError = { kind: "not_found" } | { kind: "db_error"; message: string };

export interface IOrderRepository {
  /**
   * Persist a new order. The order must have a unique ID (generated by IdGenerator).
   *
   * @param order - Order entity to persist
   * @returns The persisted order
   *
   * Errors: `db_error` — database failure.
   * Idempotent: No — calling twice with different orders creates two records.
   * Postconditions: Order is persisted with status=PENDING and retrievable via findById.
   */
  create(order: Order): Promise<Result<Order, OrderError>>;

  /**
   * Find an order by its unique ID.
   *
   * @param id - Order UUID
   * @returns The order, or `not_found` if no order exists with this ID
   *
   * Errors: `not_found` — no order with this ID exists.
   * Idempotent: Yes — reading does not mutate state.
   * Postconditions: Returns the order in its current status.
   */
  findById(id: string): Promise<Result<Order, OrderError>>;

  /**
   * Find an order by its PayMongo Checkout Session ID.
   * Used by the webhook handler to look up the order.
   */
  findByPaymongoPaymentId(paymongoPaymentId: string): Promise<Result<Order, OrderError>>;

  /** Find all orders for a given user. */
  findByUserId(userId: string): Promise<Result<Order[], OrderError>>;

  /**
   * STORY-049: admin list view of all orders, sorted by createdAt desc.
   * Optionally filter by status. The user-email search happens in the
   * use case layer (it joins against userRepo), not here.
   *
   * For large tables (thousands of orders), prefer `listPaginated` instead.
   */
  listAll(filters?: { status?: PaymentStatus }): Promise<Result<Order[], OrderError>>;

  /**
   * STORY-049 follow-up (C3 fix): paginated admin list of all orders.
   * Offset pagination — `page` is 1-based. Server-side cap of `pageSize`
   * prevents runaway queries even if a malicious caller requests pageSize=9999.
   */
  listPaginated(filters: {
    status?: PaymentStatus;
    page?: number;
    pageSize?: number;
  }): Promise<
    Result<{ orders: readonly Order[]; total: number; page: number; pageSize: number }, OrderError>
  >;

  /**
   * STORY-062: admin list view of refund requests.
   *
   * A "refund request" is any order with `refundRequestedAt IS NOT NULL`.
   * Filter by `status` to distinguish pending (no `refundProcessedAt`)
   * from processed (`refundProcessedAt IS NOT NULL`).
   *
   * The user-email search and the join against userRepo happen in the
   * use case layer, not here. The repo returns the bare order list;
   * the use case enriches with user info on the way out.
   *
   * Cursor pagination, ordered by `refundRequestedAt` desc with `id`
   * as the tiebreaker (same compound-cursor pattern as the audit log
   * list — `{refundRequestedAt.toISOString()}::{id}`).
   */
  listRefundRequests(filters: {
    status?: "pending" | "processed";
    cursor?: string;
    limit?: number;
  }): Promise<
    Result<{ orders: readonly Order[]; nextCursor: string | null; total: number }, OrderError>
  >;

  /** Persist changes to an existing order. */
  update(order: Order): Promise<Result<Order, OrderError>>;

  /**
   * STORY-P0-1 (paywall): find a PAID order for a given user + course.
   * Returns null if no such order exists. Used by the enroll use case
   * to verify that a paid course has actually been paid for.
   */
  findPaidForUserAndCourse(
    userId: string,
    courseId: string,
  ): Promise<Result<Order | null, OrderError>>;
}
