-- STORY-066: Feedback Composer.
--
-- Persists SimulatorAttempt feedback generated by the
-- ComposeAttemptFeedback use case. Each graded attempt gets one
-- feedback record (attemptId is unique). The feedback includes
-- per-dimension verdicts and remediation link recommendations.
--
-- dimensionFeedback and remediationLinks are stored as JSONB so the
-- Prisma adapter can read/write them without custom serialization
-- logic. Both columns are non-nullable — the domain entity always
-- provides an empty array rather than null.

CREATE TABLE "attempt_feedbacks" (
    "id" TEXT NOT NULL,
    "attemptId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "simulatorId" TEXT NOT NULL,
    "scenarioId" TEXT NOT NULL,
    "difficulty" TEXT NOT NULL,
    "mode" TEXT NOT NULL,
    "overallScore" INTEGER NOT NULL,
    "passed" BOOLEAN NOT NULL,
    "overallComment" TEXT NOT NULL,
    "remediationLinks" JSONB NOT NULL,
    "dimensionFeedback" JSONB NOT NULL,
    "completedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "attempt_feedbacks_pkey" PRIMARY KEY ("id")
);

-- One feedback record per attempt (idempotent compose)
CREATE UNIQUE INDEX "attempt_feedbacks_attemptId_key" ON "attempt_feedbacks"("attemptId");

-- Find all feedback for a user (dashboard, progress page)
CREATE INDEX "attempt_feedbacks_userId_idx" ON "attempt_feedbacks"("userId");
