import { describe, it, expect, vi, beforeEach } from "vitest";
import { Result } from "@/domain/shared/Result";
import { EnrollStudent } from "@/usecases/EnrollStudent";
import type { UserRepository } from "@/ports/repositories/UserRepository";
import type { CourseRepository } from "@/ports/repositories/CourseRepository";
import type { IEnrollmentRepository } from "@/ports/repositories/IEnrollmentRepository";
import type { User } from "@/domain/entities/User";
import type { Course } from "@/domain/entities/Course";
import type { Enrollment } from "@/domain/entities/Enrollment";

function makeUser(overrides: Partial<User> = {}): User {
  return {
    id: "user_01",
    email: "alice@example.com",
    firstName: "Alice",
    lastName: "V.",
    role: "STUDENT",
    subscriptionTier: "FREE",
    verificationStatus: "VERIFIED",
    enrolledCourseIds: [],
    createdAt: new Date(),
    ...overrides,
  } as User;
}

function makeCourse(overrides: Partial<Course> = {}): Course {
  return {
    id: "course_01",
    slug: "test-course",
    title: "Test Course",
    tagline: "A test course",
    description: "Description",
    price: { minor: 1000, currency: "PHP" } as Course["price"],
    curriculum: { sections: [] } as Course["curriculum"],
    coverImage: null,
    isFeatured: false,
    displayOrder: 0,
    status: "PUBLISHED",
    courseTier: "STARTER",
    previewLessonCount: 1,
    createdAt: new Date(),
    ...overrides,
  } as Course;
}

function makeEnrollment(overrides: Partial<Enrollment> = {}): Enrollment {
  return {
    id: "enroll_01",
    userId: "user_01",
    courseId: "course_01",
    status: "active",
    source: "direct",
    couponCode: null,
    couponDiscount: null,
    createdAt: new Date(),
    ...overrides,
  } as Enrollment;
}

describe("EnrollStudent", () => {
  let mockUserRepo: UserRepository;
  let mockCourseRepo: CourseRepository;
  let mockEnrollmentRepo: IEnrollmentRepository;
  let useCase: EnrollStudent;
  let idCounter = 0;

  const USER_ID = "user_01";
  const COURSE_ID = "course_01";

  beforeEach(() => {
    mockUserRepo = {
      findById: vi.fn(),
      findByEmail: vi.fn(),
      create: vi.fn(),
      update: vi.fn(),
      emailExists: vi.fn(),
      getPasswordHash: vi.fn(),
    };
    mockCourseRepo = {
      findById: vi.fn(),
      findBySlug: vi.fn(),
      listPublished: vi.fn(),
      listAll: vi.fn(),
    };
    mockEnrollmentRepo = {
      findByUserIdAndCourseId: vi.fn(),
      create: vi.fn(),
      findByUserId: vi.fn(),
      findById: vi.fn(),
    };
    useCase = new EnrollStudent({
      userRepo: mockUserRepo,
      courseRepo: mockCourseRepo,
      enrollmentRepo: mockEnrollmentRepo,
      idGen: { newId: () => `enrol_${++idCounter}` },
    });
  });

  // ── happy path ───────────────────────────────────────────

  it("enrolls user and returns enrollment", async () => {
    const user = makeUser();
    const course = makeCourse();
    const enrollment = makeEnrollment();

    vi.mocked(mockUserRepo.findById).mockResolvedValue(Result.ok(user));
    vi.mocked(mockCourseRepo.findById).mockResolvedValue(Result.ok(course));
    vi.mocked(mockEnrollmentRepo.findByUserIdAndCourseId).mockResolvedValue(null);
    // Return whatever enrollment was passed (id comes from idGen)
    vi.mocked(mockEnrollmentRepo.create).mockImplementation(
      async (e: Enrollment) => Result.ok(e),
    );
    vi.mocked(mockUserRepo.update).mockResolvedValue(Result.ok(user));

    const result = await useCase.execute({ userId: USER_ID, courseId: COURSE_ID });

    if (!Result.isOk(result)) throw new Error("expected ok");
    // id is generated by idGen.newId() — check it was called and returns a non-empty string
    expect(result.value.id).toMatch(/^[A-Za-z0-9_-]+$/);
    expect(mockEnrollmentRepo.create).toHaveBeenCalledOnce();
    expect(mockUserRepo.update).toHaveBeenCalledWith(USER_ID, {
      enrolledCourseIds: [COURSE_ID],
    });
  });

  it("appends courseId to existing enrolledCourseIds", async () => {
    const user = makeUser({ enrolledCourseIds: ["course_other"] });
    const course = makeCourse();

    vi.mocked(mockUserRepo.findById).mockResolvedValue(Result.ok(user));
    vi.mocked(mockCourseRepo.findById).mockResolvedValue(Result.ok(course));
    vi.mocked(mockEnrollmentRepo.findByUserIdAndCourseId).mockResolvedValue(null);
    vi.mocked(mockEnrollmentRepo.create).mockImplementation(
      async (e: Enrollment) => Result.ok(e),
    );
    vi.mocked(mockUserRepo.update).mockResolvedValue(Result.ok(user));

    const result = await useCase.execute({ userId: USER_ID, courseId: COURSE_ID });

    if (!Result.isOk(result)) throw new Error("expected ok");
    expect(mockUserRepo.update).toHaveBeenCalledWith(USER_ID, {
      enrolledCourseIds: ["course_other", COURSE_ID],
    });
  });

  it("enrolls with affiliate source and coupon", async () => {
    const user = makeUser();
    const course = makeCourse();

    vi.mocked(mockUserRepo.findById).mockResolvedValue(Result.ok(user));
    vi.mocked(mockCourseRepo.findById).mockResolvedValue(Result.ok(course));
    vi.mocked(mockEnrollmentRepo.findByUserIdAndCourseId).mockResolvedValue(null);
    vi.mocked(mockEnrollmentRepo.create).mockImplementation(
      async (e: Enrollment) => Result.ok(e),
    );
    vi.mocked(mockUserRepo.update).mockResolvedValue(Result.ok(user));

    const result = await useCase.execute({
      userId: USER_ID,
      courseId: COURSE_ID,
      source: "affiliate",
      couponCode: "SAVE20",
      couponDiscount: 20,
    });

    if (!Result.isOk(result)) throw new Error("expected ok");
    expect(result.value.source).toBe("affiliate");
    expect(mockEnrollmentRepo.create).toHaveBeenCalledWith(
      expect.objectContaining({
        source: "affiliate",
        couponCode: "SAVE20",
        couponDiscount: 20,
      }),
    );
  });

  // ── error cases ──────────────────────────────────────────

  it("returns user_not_found when user does not exist", async () => {
    vi.mocked(mockUserRepo.findById).mockResolvedValue(Result.err({ kind: "not_found" }));

    const result = await useCase.execute({ userId: USER_ID, courseId: COURSE_ID });

    if (!Result.isErr(result)) throw new Error("expected err");
    expect(result.error.kind).toBe("user_not_found");
  });

  it("returns course_not_found when course does not exist", async () => {
    vi.mocked(mockUserRepo.findById).mockResolvedValue(Result.ok(makeUser()));
    vi.mocked(mockCourseRepo.findById).mockResolvedValue(Result.err({ kind: "not_found" }));

    const result = await useCase.execute({ userId: USER_ID, courseId: COURSE_ID });

    if (!Result.isErr(result)) throw new Error("expected err");
    expect(result.error.kind).toBe("course_not_found");
  });

  it("returns course_not_published when course is DRAFT", async () => {
    vi.mocked(mockUserRepo.findById).mockResolvedValue(Result.ok(makeUser()));
    vi.mocked(mockCourseRepo.findById).mockResolvedValue(
      Result.ok(makeCourse({ status: "DRAFT" })),
    );

    const result = await useCase.execute({ userId: USER_ID, courseId: COURSE_ID });

    if (!Result.isErr(result)) throw new Error("expected err");
    expect(result.error.kind).toBe("course_not_published");
  });

  it("returns course_not_published when course is ARCHIVED", async () => {
    vi.mocked(mockUserRepo.findById).mockResolvedValue(Result.ok(makeUser()));
    vi.mocked(mockCourseRepo.findById).mockResolvedValue(
      Result.ok(makeCourse({ status: "ARCHIVED" })),
    );

    const result = await useCase.execute({ userId: USER_ID, courseId: COURSE_ID });

    if (!Result.isErr(result)) throw new Error("expected err");
    expect(result.error.kind).toBe("course_not_published");
  });

  it("returns already_enrolled when user already enrolled in course", async () => {
    vi.mocked(mockUserRepo.findById).mockResolvedValue(Result.ok(makeUser()));
    vi.mocked(mockCourseRepo.findById).mockResolvedValue(Result.ok(makeCourse()));
    vi.mocked(mockEnrollmentRepo.findByUserIdAndCourseId).mockResolvedValue(
      makeEnrollment(),
    );

    const result = await useCase.execute({ userId: USER_ID, courseId: COURSE_ID });

    if (!Result.isErr(result)) throw new Error("expected err");
    expect(result.error.kind).toBe("already_enrolled");
  });

  // ── defensive: already enrolled via enrolledCourseIds ───────

  it("returns already_enrolled when user.enrolledCourseIds already contains courseId", async () => {
    const user = makeUser({ enrolledCourseIds: [COURSE_ID] });
    vi.mocked(mockUserRepo.findById).mockResolvedValue(Result.ok(user));
    vi.mocked(mockCourseRepo.findById).mockResolvedValue(Result.ok(makeCourse()));

    const result = await useCase.execute({ userId: USER_ID, courseId: COURSE_ID });

    if (!Result.isErr(result)) throw new Error("expected err");
    expect(result.error.kind).toBe("already_enrolled");
  });
});
