/**
 * /admin/courses/new — admin create-course form.
 *
 * STORY-048a. Server component (form is server-action driven).
 *
 * The form has fields for everything except the curriculum (the
 * default curriculum is generated by the use case — STORY-048b adds
 * a real curriculum editor).
 */

import Link from "next/link";
import { redirect } from "next/navigation";
import { buildContainer } from "@/composition/container";
import { requireAdmin } from "@/lib/auth";
import { TopBar } from "@/components/admin/TopBar";
import { Card } from "@/components/ui";
import { createCourseAction } from "@/app/actions/createCourse.action";
import type { CreateCourseInput } from "@/usecases/CreateCourse";
import styles from "./page.module.css";

export default async function NewCoursePage() {
  await requireAdmin();

  async function handleSubmit(formData: FormData) {
    "use server";
    const input: CreateCourseInput = {
      id: String(formData.get("id") ?? "").trim(),
      slug: String(formData.get("slug") ?? "").trim(),
      title: String(formData.get("title") ?? "").trim(),
      tagline: String(formData.get("tagline") ?? "").trim(),
      description: String(formData.get("description") ?? "").trim(),
      priceMinor: parseInt(String(formData.get("priceMinor") ?? "0"), 10) || 0,
      courseTier: (String(formData.get("courseTier") ?? "STARTER")) as
        | "STARTER"
        | "PRO"
        | "PREVIEW",
      previewLessonCount:
        parseInt(String(formData.get("previewLessonCount") ?? "1"), 10) || 1,
      isFeatured: formData.get("isFeatured") === "on",
      displayOrder: parseInt(String(formData.get("displayOrder") ?? "0"), 10) || 0,
      coverImage: String(formData.get("coverImage") ?? "").trim() || null,
      status: (String(formData.get("status") ?? "DRAFT")) as
        | "DRAFT"
        | "PUBLISHED"
        | "ARCHIVED",
      defaultCurriculum: {
        sectionTitle:
          String(formData.get("sectionTitle") ?? "Getting Started").trim() ||
          "Getting Started",
        lessonTitle:
          String(formData.get("lessonTitle") ?? "Welcome").trim() || "Welcome",
      },
    };

    const result = await createCourseAction(input);
    if (result.ok) {
      redirect(`/admin/courses/${result.value.courseId}`);
    }
    // On error, fall through to render an error message below
  }

  return (
    <div>
      <Link href="/admin/courses" className={styles.backLink}>
        ← Back to courses
      </Link>

      <TopBar title="Add course" subtitle="Create a new course (DRAFT by default)" />

      <form action={handleSubmit} className={styles.form}>
        <Card padding="comfortable">
          <h2 className={styles.sectionTitle}>Basics</h2>
          <div className={styles.grid}>
            <label className={styles.field}>
              <span className={styles.label}>Course ID (ULID)</span>
              <input
                name="id"
                type="text"
                required
                pattern="[a-zA-Z0-9_-]+"
                className={styles.input}
                placeholder="course_01J3X..."
              />
              <span className={styles.help}>
                Unique identifier. Use a ULID or similar.
              </span>
            </label>

            <label className={styles.field}>
              <span className={styles.label}>Slug</span>
              <input
                name="slug"
                type="text"
                required
                pattern="[a-z0-9]+(?:-[a-z0-9]+)*"
                className={styles.input}
                placeholder="intro-to-amazon"
              />
              <span className={styles.help}>
                Lowercase letters, numbers, and hyphens. Used in the URL.
              </span>
            </label>

            <label className={styles.field}>
              <span className={styles.label}>Title</span>
              <input
                name="title"
                type="text"
                required
                className={styles.input}
                placeholder="Intro to Amazon FBA"
              />
            </label>

            <label className={styles.field}>
              <span className={styles.label}>Tagline</span>
              <input
                name="tagline"
                type="text"
                className={styles.input}
                placeholder="Your first steps to Amazon FBA"
              />
            </label>

            <label className={`${styles.field} ${styles.fullWidth}`}>
              <span className={styles.label}>Description</span>
              <textarea
                name="description"
                rows={4}
                className={styles.textarea}
                placeholder="A complete course for Filipino VAs..."
              />
            </label>
          </div>
        </Card>

        <Card padding="comfortable">
          <h2 className={styles.sectionTitle}>Pricing & access</h2>
          <div className={styles.grid}>
            <label className={styles.field}>
              <span className={styles.label}>Price (PHP, in centavos)</span>
              <input
                name="priceMinor"
                type="number"
                min="0"
                step="1"
                required
                defaultValue="0"
                className={styles.input}
              />
              <span className={styles.help}>
                100 = ₱1.00. Use 0 for free courses.
              </span>
            </label>

            <label className={styles.field}>
              <span className={styles.label}>Course tier</span>
              <select name="courseTier" defaultValue="STARTER" className={styles.input}>
                <option value="STARTER">Starter</option>
                <option value="PRO">Pro</option>
                <option value="PREVIEW">Preview only</option>
              </select>
            </label>

            <label className={styles.field}>
              <span className={styles.label}>Preview lessons</span>
              <input
                name="previewLessonCount"
                type="number"
                min="0"
                step="1"
                defaultValue="1"
                className={styles.input}
              />
              <span className={styles.help}>
                How many lessons non-enrolled users can preview.
              </span>
            </label>

            <label className={styles.field}>
              <span className={styles.label}>Display order</span>
              <input
                name="displayOrder"
                type="number"
                step="1"
                defaultValue="0"
                className={styles.input}
              />
            </label>
          </div>
        </Card>

        <Card padding="comfortable">
          <h2 className={styles.sectionTitle}>Default curriculum (placeholder)</h2>
          <p className={styles.help}>
            A real curriculum editor lands in STORY-048b/c. For now, the
            course is created with one section and one lesson using the
            titles below — the admin can replace them later.
          </p>
          <div className={styles.grid}>
            <label className={styles.field}>
              <span className={styles.label}>Default section title</span>
              <input
                name="sectionTitle"
                type="text"
                defaultValue="Getting Started"
                className={styles.input}
              />
            </label>

            <label className={styles.field}>
              <span className={styles.label}>Default lesson title</span>
              <input
                name="lessonTitle"
                type="text"
                defaultValue="Welcome"
                className={styles.input}
              />
            </label>
          </div>
        </Card>

        <Card padding="comfortable">
          <h2 className={styles.sectionTitle}>Publishing</h2>
          <div className={styles.grid}>
            <label className={styles.field}>
              <span className={styles.label}>Status</span>
              <select name="status" defaultValue="DRAFT" className={styles.input}>
                <option value="DRAFT">Draft (hidden from public)</option>
                <option value="PUBLISHED">Published (visible)</option>
              </select>
            </label>

            <label className={styles.field}>
              <span className={styles.label}>Cover image URL</span>
              <input
                name="coverImage"
                type="url"
                className={styles.input}
                placeholder="https://..."
              />
            </label>

            <label className={`${styles.field} ${styles.checkboxField}`}>
              <input name="isFeatured" type="checkbox" />
              <span>Feature on the homepage</span>
            </label>
          </div>
        </Card>

        <div className={styles.actions}>
          <Link href="/admin/courses" className={styles.cancelButton}>
            Cancel
          </Link>
          <button type="submit" className={styles.submitButton}>
            Create course
          </button>
        </div>
      </form>
    </div>
  );
}
