/**
 * IOAuthBroker — port for one OAuth2 provider's wire protocol.
 *
 * P1-04 (PR-D). The use-case layer drives the flow (authorize URL,
 * code exchange, profile fetch) without knowing HTTP. PKCE values
 * are generated by the caller and passed in, so the broker stays
 * a pure protocol translator.
 *
 * Implementations: GoogleOAuthBroker (prod, fetch-based),
 * StubOAuthBroker (tests).
 */

import type { Result } from "@/domain/shared/Result";
import type { OAuthProvider } from "@/domain/entities/OAuthAccount";

export interface OAuthProfile {
  providerUserId: string;
  email: string;
  emailVerified: boolean;
  name: string | null;
}

export type OAuthBrokerError =
  | { kind: "provider_error"; message: string }
  | { kind: "network_error"; message: string }
  | { kind: "invalid_response"; message: string };

export interface AuthorizeUrlInput {
  state: string;
  codeChallenge: string;
  redirectUri: string;
}

export interface ExchangeCodeInput {
  code: string;
  codeVerifier: string;
  redirectUri: string;
}

export interface OAuthTokens {
  accessToken: string;
  expiresAt: Date | null;
}

export interface IOAuthBroker {
  readonly provider: OAuthProvider;
  buildAuthorizeUrl(input: AuthorizeUrlInput): string;
  exchangeCode(input: ExchangeCodeInput): Promise<Result<OAuthTokens, OAuthBrokerError>>;
  fetchProfile(accessToken: string): Promise<Result<OAuthProfile, OAuthBrokerError>>;
}
